### ISSUE TITLE
code

### ISSUE THREAD

**Issue by brianbalgley** [matthieu-david/SpecOMS#1]
Hi! Your paper is very interesting. Are you going to deposit any code here? Thanks!

**Comment by matthieu-david** [comment]
Hi,
Thanks for the feedback.
There will be some code deposit here though not any time soon. If you feel the need for some additional information on implementation details, feel free to ask, I'll be glad to discuss them.
Warm regards.

**Comment by brianbalgley** [comment]
Thanks! And sorry... where can the current version be downloaded? I thought the publication said it was here?

**Comment by matthieu-david** [comment]
You're welcome.
The current version can be downloaded in the "release" section from this github page : https://github.com/matthieu-david/SpecOMS/releases
