### ISSUE TITLE
Source code still unavailable

### ISSUE THREAD

**Issue by SamGG** [matthieu-david/SpecOMS#3]
Hi,
Very interesting approach. I am interested in the SpecXtract part of your methodology for searching a peak list versus a FASTA database or versus a peak lists database. I thought I could find this code part in the source. Unfortunately, the source code is not available. The zip and tar.gz files contains only license and readme. I don't think it's worth calling them source code.
The "source" directory within the release file should be renamed as "input", as this is somehow misleading.
Is there any implementation of the SpecXtract with source code?
Best.

**Comment by matthieu-david** [comment]
Dear SamGG,

I apologize for the late answer.

Up to now we do not provide the source code ; the source.zip and source.tar are github automatically generated files (if you know how to remove them from the release I would be happy to hear). Explanations regarding the general algorithm can be found in the publication SpecTrees: An Efficient Without a Priori Data Structure for MS/MS Spectra Identification. The exact implementation however varies from the high-level description for performance and technical reasons.

If you want more detailed explanations on the algorithms, I am very happy to help you. You can get in touch with me directly : matthieu.david@univ-nantes.fr

Best regards,

M.D.
